version: '3.9'
services:
  express-notes-app:
    build: .
    ports: 
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://db/express-notes-app
      - SECRET=replaceme
      - NODE_ENV=production
    links:
      - db
  db:
    image: mongo:5.0.6